/*
LFS261
Jenkisnsfile del ejemplo de una app java Instavote - Parte App Vote en Python
https://github.com/choncba/example-voting-app
*/
pipeline {
    // agent {
    //     docker{
    //         image 'python:2.7.16-slim'
    //         args '-u root' // Permite que pip instale paquetes dentro del contenedor
    //     }
    // }
    agent none  // Redefino el agente en cada stage

    stages {                                    // Defino las etapas
        stage('build') {
            agent {
                docker{
                    image 'python:2.7.16-slim'
                    args '-u root' // Permite que pip instale paquetes dentro del contenedor
                }
            }
            when{                               // Ejecuto en cualquier branch, pero
                changeset '**/vote/**'        // Solo se ejecuta si hago cambios en la carpeta vote
            }
            steps {                             // primera etapa, compilar
                echo 'Building vote App...'
                dir('vote'){                  // Cambio al directorio result
                    sh 'pip install -r requirements.txt'            // instalo los requerimientos
                }
            }
        }
        
        stage('test') {                         // Segunda etapa, test
            agent {
                docker{
                    image 'python:2.7.16-slim'
                    args '-u root' // Permite que pip instale paquetes dentro del contenedor
                }
            }
            when{
                changeset '**/vote/**'        // Solo se ejecuta si hago cambios en la carpeta result
            }
            steps {
                echo 'Running Nose Tests on vote App...'
                dir('vote'){
                    sh 'pip install -r requirements.txt'            // instalo los requerimientos
                    sh 'nosetests -v'
                }
            }
        }

        stage('docker-package'){
            agent any 
            when{
                changeset '**/vote/**'  
                //branch 'master'         
            }
            steps{
              echo 'Packaging vote app with docker'
              script{
                docker.withRegistry('https://index.docker.io/v1/', 'dockerhublogin') {
                    def workerImage = docker.build("lrbono/vote:v${env.BUILD_ID}", "./vote")
                    workerImage.push()
                    workerImage.push("${env.BRANCH_NAME}")
                }
              }
            }
        }
    }

    post{                                       // Post implementación
    always{                                 // Indica ejecuatar siempre
            echo 'Pipeline for Vote App is complete!'
        }
    }
}

